Lab2
sergey-berezin/441_2_sazonov pull request #2
Opened 2023-10-06 22:16 UTC by Jeratt

2023-10-06 22:59 UTC, Jeratt commented
Программа пока не вполне идеальна, есть небольшие проблемы с асинхронной обработкой, которые хотелось бы обсудить на технологической практике, однако всё остальное, кажется, сделано. Не претендую на достаточный для зачёта задания пулл-реквест, однако надеюсь, что с ним обсудить вышеупомянутые вопросы будет проще

2023-10-09 20:25 UTC, Jeratt commented
Поправил асинхронность, теперь она действительно есть) (Task.Factory.StartNew(...))
Есть подозрения, что у меня на устройстве по какой-то причине всё ещё подвисает рендеринг, однако UI не заблокирован - проверки показывают работоспособность кнопки "Interrupt model" - я скачал датасет с большим количеством котиков, на котором хорошо видно, что не все картинки успевают обработаться) 

P.S. тем временем, кажется, в QT рендеринг, UI элементы и управление разделены в 3 отдельных потока по умолчанию и не могут так блокироваться как в WPF...

2023-10-14 18:08 UTC, sergey-berezin requested changes

2023-10-14 18:08 UTC, sergey-berezin commented on ViewModel/AsyncCommand.cs
> +        public Task ExecuteAsync()
Зачем нужен этот метод?

2023-10-14 18:08 UTC, sergey-berezin commented on ViewModel/CommandManager.cs
> +    public static class SimpleCommandManager
Как используется этот класс?

2023-10-14 18:08 UTC, sergey-berezin commented on ViewModel/ViewData.cs
> +        private async Task ChooseNewDirectoryAsync()
Этот обработчик может вызываться пока идёт распознавание?

2023-10-14 18:08 UTC, sergey-berezin commented on ViewModel/ViewData.cs
> +        private void CancelDetectionFunction(object sender)
Что будет, если вызвать этот обработчик до начала распознавания или два раза?

2023-10-16 10:13 UTC, merged